#!/bin/sh

# The MIT License (MIT)
#▫
# Copyright (c) 2022 Yury Gribov
#▫
# Use of this source code is governed by The MIT License (MIT)
# that can be found in the LICENSE.txt file.

set -eu
#set -x

if echo "$0" | grep -q ++; then
  real_exe=g++
  type=c++
else
  real_exe=gcc
  type=c
fi

# Check that versions of clang and libclang match
CLANG_VERSION=$(clang --version | sed -n -e 's/clang version \([0-9.]\+\).*/\1/p')
LIBCLANG_VERSION=$(llvm-config --version)
if test $CLANG_VERSION != $LIBCLANG_VERSION; then
  echo >&2 "clang and libclang versions do not match: $CLANG_VERSION vs $LIBCLANG_VERSION"
fi

ROOT=$(dirname $0)/..

# Why is libtooling interface so useless...
FILES=$(echo "$@" | grep -o '[^ ]\+\.\(cc\|cpp\|c\|cxx\|C\)\( \|$\)' || true)
OPTS=$(echo "$@" | sed -e 's/[^ ]\+\.\(cc\|cpp\|c\|cxx\|C\)\( \|$\)//g')

if test -n "$FILES" && ! (echo -- "$OPTS" | grep -q -- '-\([EM]\|MM\)\>'); then
  # Strip unhandled flags (-flto=jobserver causes clang to malfunction)
  OPTS=$(echo $OPTS | sed -e 's/-f\(lifetime-dse\|abi-version\|var-tracking\|lto\)[^ ]*//g')
  # Add std includes
  INCLUDES=$(clang -x $type -E -Wp,-v /dev/null 2>&1 | awk '/^ \//{ORS=" "; print "-I" $1}')
  # Disable all warnings
  WARNS='-fpermissive -w -Wno-everything -Wno-error'
  if ! $ROOT/bin/SortChecker $FILES -- $OPTS -I$ROOT/include $INCLUDES $WARNS; then
    echo "SortChecker: failed to compile $FILES"
  fi
fi
/usr/bin/$real_exe "$@" -I$ROOT/include
