#!/bin/sh

# The MIT License (MIT)
#▫
# Copyright (c) 2022 Yury Gribov
#▫
# Use of this source code is governed by The MIT License (MIT)
# that can be found in the LICENSE.txt file.

set -eu
#set -x

if echo "$0" | grep -q ++; then
  real_exe=g++
  type=c++
else
  real_exe=gcc
  type=c
fi

ROOT=$(dirname $0)/..

# Why is libtooling interface so useless...
FILES=$(echo "$@" | grep -o '[^ ]\+\.\(cc\|cpp\|c\|cxx\|C\)\( \|$\)' || true)
OPTS=$(echo "$@" | sed -e 's/[^ ]\+\.\(cc\|cpp\|c\|cxx\|C\)\( \|$\)//g')

if test -n "$FILES" && ! (echo -- "$OPTS" | grep -q -- '-\([EM]\|MM\)\>'); then
  # Strip unhandled flags (-flto=jobserver causes clang to malfunction)
  OPTS=$(echo $OPTS | sed -e 's/-f\(lifetime-dse\|abi-version\|var-tracking\|lto\)[^ ]*//g')
  # Add std includes
  INCLUDES=$(clang -x $type -E -Wp,-v /dev/null 2>&1 | awk '/^ \//{ORS=" "; print "-I" $1}')
  if test -n "${GITHUB_ACTIONS:-}" && grep -q 20.04 /etc/lsb-release; then
    # FIXME: for some reason presense of clang's compiler dirs
    # ruin search for correct stdint.h in GH actions environment
    INCLUDES=$(echo $INCLUDES | sed 's/[^ ]*clang[^ ]*//')
  fi
  # Disable all warnings
  WARNS='-fpermissive -w -Wno-everything -Wno-error'
  if ! $ROOT/bin/SortChecker $FILES -- $OPTS -I$ROOT/include $INCLUDES $WARNS; then
    echo "SortChecker: failed to compile $FILES"
  fi
fi
/usr/bin/$real_exe "$@" -I$ROOT/include
