#!/bin/sh

# The MIT License (MIT)
# 
# Copyright (c) 2022 Yury Gribov
# 
# Use of this source code is governed by The MIT License (MIT)
# that can be found in the LICENSE.txt file.

set -eu
#set -x

if echo "$0" | grep -q ++; then
  exe=g++
else
  exe=gcc
fi

ROOT=$(dirname $0)/..

# Why is libtooling interface so useless...
FILES=$(echo "$@" | grep -o '[^ ]\+\.\(cc\|cpp\|c\|cxx\|C\)\( \|$\)' || true)
OPTS=$(echo "$@" | sed -e 's/[^ ]\+\.\(cc\|cpp\|c\|cxx\|C\)\( \|$\)//g')

test -z "$FILES" || $ROOT/bin/SortChecker $FILES -- $OPTS
/usr/bin/$exe "$@" -I$ROOT/include
