name: CI
on:
  push:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
    - '.gitignore'
  pull_request:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
    - '.gitignore'
jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cxx: [g++]
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: scripts/install_deps.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Run tests
      run: scripts/travis.sh
